config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'accounts#index'
  resources :sales_reps, only: [:index, :show]

  resources :accounts, only: :index do 
    collection do 
      post(:import)
      get(:accounts_search_table)
    end
  end

  resources :specimens, only: [] do 
    collection do
      get 'accession_log', to: 'specimens#accession_log', as: 'accession_log'
      get 'eia_report/pick_a_date', to: 'specimens#pick_a_date', as: 'pick_a_date'
      get 'eia_report/generate_report', to: 'specimens#generate_report'
      get(:generate_report)
      get(:check_for_report)
    end
  end

  namespace :api, :defaults => { format: :json } do 
    namespace :v1 do
      get 'requisition/:id' => 'accounts#show'
      resources :accounts, only: :index
      resources :specimens, only: [:index, :create, :update]
    end
    # namespace :v2 do 
    # end
  end
end

# == Route Map
#
#      Prefix Verb URI Pattern Controller#Action
# rails_admin      /admin      RailsAdmin::Engine
#
# Routes for RailsAdmin::Engine:
#   dashboard GET         /                                      rails_admin/main#dashboard
#       index GET|POST    /:model_name(.:format)                 rails_admin/main#index
#         new GET|POST    /:model_name/new(.:format)             rails_admin/main#new
#      export GET|POST    /:model_name/export(.:format)          rails_admin/main#export
# bulk_delete POST|DELETE /:model_name/bulk_delete(.:format)     rails_admin/main#bulk_delete
# bulk_action POST        /:model_name/bulk_action(.:format)     rails_admin/main#bulk_action
#        show GET         /:model_name/:id(.:format)             rails_admin/main#show
#        edit GET|PUT     /:model_name/:id/edit(.:format)        rails_admin/main#edit
#      delete GET|DELETE  /:model_name/:id/delete(.:format)      rails_admin/main#delete
# show_in_app GET         /:model_name/:id/show_in_app(.:format) rails_admin/main#show_in_app
#

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id                   :integer          not null, primary key
#  prefix               :string(255)
#  company_name         :string(255)
#  notes                :string(255)
#  sales_rep_id         :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  has_sample_collector :boolean          default(FALSE)
#
# Indexes
#
#  index_accounts_on_sales_rep_id  (sales_rep_id)
#
# Foreign Keys
#
#  fk_rails_01911985a2  (sales_rep_id => sales_reps.id)
#

class Account < ActiveRecord::Base
  belongs_to :sales_rep
  has_many :account_providers
  has_many :providers, through: :account_providers
  has_many :base_panels, dependent: :destroy, inverse_of: :account
  has_many :account_numbers, dependent: :destroy, inverse_of: :account
  has_many :phone_numbers, through: :account_numbers
  has_many :addresses, through: :account_numbers
  has_many :account_report_delivery_types
  has_many :report_delivery_types, through: :account_report_delivery_types
  has_many :requisition_ranges, :inverse_of => :account
  has_many :specimens, dependent: :destroy, inverse_of: :account
  accepts_nested_attributes_for :base_panels, allow_destroy: true
  accepts_nested_attributes_for :account_numbers, allow_destroy: true
  accepts_nested_attributes_for :requisition_ranges, allow_destroy: true

  validates_presence_of :prefix #, :sales_rep
  validates_length_of :prefix, :notes, :company_name, maximum: 255
  validates_uniqueness_of :prefix

  def self.render_by_req_num(requisition_number)
    requisition_range = RequisitionRange.find_by!(
      "starts_at <= :req_number AND ends_at >= :req_number",
      :req_number => requisition_number
    )

    return JSON.pretty_generate(
      requisition_range.account.as_json(
        include: [
          :sales_rep,
          :providers,
          :base_panels,
          :account_numbers,
          :phone_numbers,
          :addresses,
          :report_delivery_types,
          :requisition_ranges
        ]
      )
    )
  end

  def prefix=(prefix)
    super prefix.to_s.upcase
  end

  def name
    "#{prefix} - #{company_name}"
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    respond_to do |format|
      format.html do
        render
      end
      format.json do
        render json: AccountSearchDatatablesAdapter.new(params)
      end
    end
  end

  def accounts_search_table
    render partial: 'accounts/accounts_search_table'
  end

  def import
    begin
      spreadsheet = Roo::Spreadsheet.open(params[:file].path)
      sheet = spreadsheet.sheet(0)
      AccountsImporter.new.import sheet
    rescue AccountsImporter::ImportError => e   
      tempfile = Tempfile.open("import_errors") { |f| f << e.errors.to_json }
      return render json: { tempfile: tempfile.path, errors: e.errors }
    end
    redirect_to root_url, notice: "Accounts Imported."
  end
end

app/controllers/api/v1/accounts_controller.rb
class API::V1::AccountsController < ApplicationController
  def index
    render json: Account.all
  end

	def show
		begin
			render json: Account.render_by_req_num(params[:id])
		rescue => e
			error_message = e.message
			if e.class == ActiveRecord::RecordNotFound
				error_message = "Could not find Account for requisition number #{params[:id]}"
			end
			render json: { :errors => error_message}, status: 422
		end
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_accounts_search_table.html.erb
<div class="searchOptions">
  <label for="search-by">Search by:</label>
  <select id="search-by" class="ui selection dropdown search-by">
    <option value="accounts" selected>Account</option>
    <option value="addresses">Address</option>
    <option value="providers">Providers</option>
    <option value="phone_numbers">Contact</option>
    <option value="sales_reps">Account Rep</option>
    <option value="base_panels">Panel Adjustments</option>
    <option value="report_delivery_types">Report Delivery Type</option>
  </select>
</div>

<table id="example" class="table table-bordered table-hover cell-borders row-border order-column" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Prefix</th>
      <th>Account </th>
      <th>Company</th> 
      <th>Address</th>
      <th>Providers &amp; NPI Number</th>
      <th>Contact</th>
      <th>Account Rep</th>
      <th>Panel Adjustment</th>
      <th>Report Delivery</th>
      <th>Sample Collector</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>Prefix</th>
      <th>Account </th>
      <th>Company</th> 
      <th>Address</th>
      <th>Providers &amp; NPI Number</th>
      <th>Contact</th>
      <th>Account Rep</th>
      <th>Panel Adjustment</th>
      <th>Report Delivery</th>
      <th>Sample Collector</th>
    </tr>
  </tfoot>
  <tbody>
  </tbody>
</table>

app/views/accounts/index.html.erb
<div class="table-wrapper">
    <br>
    <div class="hidden">
      <%= form_tag import_accounts_path, multipart: true do %>
        <%= file_field_tag :file, class: "ui selection dropdown" %>
        <%= submit_tag "Import", class: "big ui download primary button" %>
      <% end %>
      <br>  
      <div id="example_filter" class="requisition-search dataTables_filter ui input">
        <div>
          <label>Requisition: <input id="requisition-number" type="text" aria-controls="example"></label>
        </div>
      </div>
    </div>

    <%= render 'accounts_search_table' %>
</div>